name: Unit Test With Coverage

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.303

    - name: Restore dependencies
      run: dotnet restore   

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test  -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=opencover --no-build --verbosity normal Mochi.UnitTests/
      
    - name: Create Test Coverage Badge
      uses: simon-k/dotnet-code-coverage-badge@v1.0.0
      id: create_coverage_badge
      with:
        label: Unit Test Coverage
        color: blue
        path: Mochi.UnitTests/TestResults/coverage.opencover.xml
        gist-filename: mochi-code-coverage.json
        gist-id: 58977bdd8994a6eaaa2345e9a70c33d6
        gist-auth-token: ${{ secrets.GIST_AUTH_TOKEN }}       

    - name: Print code coverage
      run: echo "Code coverage percentage ${{steps.create_coverage_badge.outputs.percentage}}%"